export const BOOK_QUERY_KEY = {
  BOOK_LIST_KEY: "BOOK_LIST_KEY",
  BOOK_DETAIL_KEY: "BOOK_DETAIL_KEY",
  BOOK_SEARCH_KEY: "BOOK_SEARCH_KEY",
};

export const SEARCH_QUERY_KEY = {
  SEARCH_RESULT_KEY: "SEARCH_RESULT_KEY",
};
